Repository LikeLion-at-DGU/moin_frontend, pull requests merged in 2023-07, with the labels that each got.

#2 feat : 초기셋팅-2
  .gitignore
  index.html
  src/assets/react.svg
  src/components/Header.jsx
  src/components/layouts/NavBar.jsx
  src/components/layouts/style.jsx
  src/components/main/mainCard/MainCard.jsx
  src/components/main/mainCard/style.jsx
  src/components/main/mainSearch/MainSearch.jsx
  src/components/main/mainSearch/style.jsx
  src/pages/Auth/login.jsx
  src/pages/main/Main.jsx
  src/pages/manito/Manito.jsx
  src/router.jsx
  src/style/globalStyle.js
Labels: enhancement, 유진

#3 :memo: Update: router v6으로 수정
  src/App.jsx
  src/components/layouts/NavBar.jsx
  src/main.jsx
  src/pages/Error/NotFound.jsx
  src/pages/Error/style.jsx
  src/router.jsx
Labels: enhancement, 서현

#5 💄 style : font 적용 및 폴더 추가
  src/assets/fonts/Font.css
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/pages/about/About.jsx
  src/pages/about/style.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/AiServiceList.jsx
  src/pages/ai/style.jsx
  src/pages/profile/Profile.jsx
  src/pages/profile/style.jsx
  src/pages/sugesstion/Sugesstion.jsx
  src/pages/sugesstion/style.jsx
  src/style/globalStyle.js
Labels: enhancement, 희찬

#8 ✨ Feat : prettier 설정하기
  .prettierrc
  src/main.jsx
  src/pages/sugesstion/Sugesstion.jsx
  src/pages/suggestion/Suggestion.jsx
  src/pages/suggestion/style.jsx
Labels: enhancement, 유진
