Repository LikeLion-at-DGU/moin_frontend, pull requests merged in 2023-08, with the labels that each got.

#10 :sparkles: Feat: AIDetail, community router
  .prettierrc
  src/App.jsx
  src/components/layouts/NavBar.jsx
  src/components/main/mainAiList/AiService.jsx
  src/components/main/mainAiList/MainAiServiceList.jsx
  src/components/main/mainAiList/style.jsx
  src/components/main/mainBanner/Banner.jsx
  src/components/main/mainBanner/MainBannerList.jsx
  src/components/main/mainBanner/style.jsx
  src/main.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/AiServiceList.jsx
  src/pages/community/Community.jsx
  src/pages/main/Main.jsx
  src/pages/main/style.jsx
  src/pages/profile/Profile.jsx
  src/pages/suggestion/Suggestion.jsx
  src/router.jsx
Labels: enhancement, 서현

#11 :sparkles: Feat: router 페이지 추가
  package-lock.json
  package.json
  src/App.jsx
  src/components/layouts/NavBar.jsx
  src/components/layouts/style.jsx
  src/components/main/mainAiList/style.jsx
  src/components/main/mainBanner/Banner.jsx
  src/components/main/mainBanner/MainBannerList.jsx
  src/components/main/mainBanner/banner1.png
  src/components/main/mainBanner/banner2.png
  src/components/main/mainBanner/style.jsx
  src/components/main/mainCard/MainCard.jsx
  src/components/main/mainSearch/MainSearch.jsx
  src/components/main/mainSearch/style.jsx
  src/pages/community/Community.jsx
  src/pages/main/Main.jsx
  src/pages/main/style.jsx
  src/pages/notice/About.jsx
  src/pages/notice/style.jsx
  src/router.jsx
  src/style/theme.js
Labels: enhancement, 서현

#22 ✨feat : 로그인, 로그아웃, 마이페이지 연결 및 레이아웃 + 배포
  dist/assets/banner1-203ac753.png
  dist/assets/banner2-5b1c62b3.png
  dist/assets/index-98ffa714.js
  dist/assets/index-c542050c.css
  dist/assets/moin_logo-06bb1d8f.png
  dist/index.html
  dist/vite.svg
  src/assets/images/icon/Google.png
  src/assets/images/icon/google.png
  src/assets/images/moin_logo.png
  src/components/auths/authLogin/AuthLoginForm.jsx
  src/components/auths/authLogin/AuthLoginTitle.jsx
  src/components/auths/authLogin/style.jsx
  src/components/layouts/NavBar.jsx
  src/components/layouts/style.jsx
  src/components/main/mainBanner/MainBannerList.jsx
  src/main.jsx
  src/pages/Auth/login.jsx
  src/pages/Auth/style.jsx
  src/pages/auths/Login.jsx
  src/pages/auths/style.jsx
  src/pages/errors/NotFound.jsx
  src/pages/errors/style.jsx
  src/pages/profile/Profile.jsx
  src/router.jsx
  src/style/globalStyle.js
  src/style/theme.js
Labels: enhancement, 기능개발, wontfix, 희찬

#23 💄 Style: Mainpage FontSize
  package-lock.json
  package.json
  src/App.jsx
  src/components/layouts/style.jsx
  src/components/like/style.jsx
  src/components/main/mainAiList/AiService.jsx
  src/components/main/mainAiList/MainAiServiceList.jsx
  src/components/main/mainAiList/keyword/Keyword.jsx
  src/components/main/mainAiList/keyword/style.jsx
  src/components/main/mainAiList/style.jsx
  src/components/main/mainBanner/MainBannerList.jsx
  src/components/main/mainBanner/pagination.css
  src/components/main/mainCategory/style.jsx
  src/components/main/mainSearch/MainSearch.jsx
  src/components/main/mainSearch/style.jsx
  src/components/main/mainSelector/MainSelector.jsx
  src/components/paging/ListView.jsx
  src/components/paging/Paging.jsx
  src/components/paging/style.css
  src/components/selector/Selector.jsx
  src/components/selector/style.jsx
  src/components/star/Star.jsx
  src/components/star/style.jsx
  src/pages/main/Main.jsx
  src/pages/main/style.jsx
Labels: enhancement, 서현, 디자인

#24 ✨ Feat : AI Service 디테일 페이지 - 소개 부분
  package-lock.json
  package.json
  src/assets/images/icon/company.png
  src/assets/images/icon/share.png
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/style.jsx
Labels: enhancement, 유진, 디자인

#29 feat : 유저 로그인 연동
  .env
  Dockerfile
  dist/assets/index-78e7cdfd.css
  dist/assets/index-98ffa714.js
  dist/assets/index-a4b0b43f.js
  dist/assets/index-c542050c.css
  dist/index.html
  dist/mainlogo.svg
  dist/vite.svg
  index.html
  package-lock.json
  package.json
  public/mainlogo.svg
  public/vite.svg
  src/api/axios.js
  src/assets/images/icon/kakao.png
  src/components/auths/authSocialButton/authSocialButton.jsx
  src/components/auths/authSocialButton/style.jsx
  src/components/layouts/NavBar.jsx
  src/context/authState.jsx
  src/main.jsx
  src/pages/auths/Login.jsx
  src/pages/auths/style.jsx
  src/pages/profile/Profile.jsx
Labels: enhancement, 기능개발, 희찬

#32 ✨ Feat : AI Service 디테일 페이지 - 탭 구현 & 이용 꿀팁
  package-lock.json
  package.json
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/style.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#33 🐛 Fix: 경로 오류 수정
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
Labels: bug, 유진

#36 ✨ Feat : AI Service 디테일 페이지 - 이용후기 댓글 구현
  src/assets/images/icon/review.png
  src/assets/images/icon/starAvg.png
  src/assets/images/icon/starMy.png
  src/assets/images/icon/style.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#37 :sparkles: Feat: sideBar
  src/App.jsx
  src/components/common/paging/ListView.jsx
  src/components/common/paging/style.jsx
  src/components/layouts/NavBar.jsx
  src/components/layouts/style.jsx
  src/components/main/mainAiList/MainAiServiceList.jsx
  src/components/main/mainAiList/style.jsx
  src/components/main/mainBanner/style.jsx
  src/pages/main/style.jsx
  src/style/globalStyle.js
Labels: enhancement, 서현, 디자인

#38 ✨feat: 로그인, 회원가입, 비밀번호 찾기, 비밀번호 변경 개발
  src/assets/images/icon/authBannerIcon.svg
  src/components/auths/authLogin/AuthLoginForm.jsx
  src/components/auths/authLogin/style.jsx
  src/pages/auths/auth/Auth.jsx
  src/pages/auths/auth/style.jsx
  src/pages/auths/authLogin/AuthLogin.jsx
  src/pages/auths/authLogin/style.jsx
  src/pages/auths/authReset/AuthReset.jsx
  src/pages/auths/authReset/style.jsx
  src/pages/auths/authSignup/AuthSignup.jsx
  src/pages/auths/authSignup/style.jsx
  src/pages/profile/profileChangePassword/ProfileChangePassword.jsx
  src/pages/profile/profileChangePassword/style.jsx
  src/pages/profile/profileMain/ProfileMain.jsx
  src/pages/profile/profileMain/style.jsx
  src/pages/profile/profileModify/ProfileModify.jsx
  src/router.jsx
Labels: enhancement, 기능개발, 희찬, 디자인

#40 ✨ Feat : AI Service 디테일 페이지 - 변경사항 적용 및 기능 구현
  package-lock.json
  package.json
  src/assets/images/icon/share.png
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDescription/style.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/common/keyword/Keyword.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/style.jsx
  src/router.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#41 ✨ Feat: Footer 추가
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/aiServiceList/AiService.jsx
  src/components/common/keyword/Keyword.jsx
  src/components/common/keyword/style.jsx
  src/components/common/searchForm/style.jsx
  src/components/common/star/Star.jsx
  src/components/common/star/style.jsx
  src/components/layouts/footer/FooterBar.jsx
  src/components/layouts/footer/style.jsx
  src/pages/main/Main.jsx
  src/pages/search/Search.jsx
  src/pages/search/style.jsx
  src/router.jsx
Labels: enhancement, 서현, 디자인

#42 ✨ Feat: MainPage - pagination, selectorSort
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/aiServiceList/AiServiceList.jsx
  src/components/common/paging/Paging.jsx
  src/components/common/paging/style.css
  src/components/common/paging/style.jsx
  src/components/common/selector/Selector.jsx
  src/pages/main/Main.jsx
Labels: enhancement, 기능개발, 서현, 디자인

#43 ✨ Feat : AI Service 디테일 페이지 - 이용 후기 기능 구현
  package-lock.json
  package.json
  src/assets/images/icon/review.png
  src/assets/images/icon/reviewList.png
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#44 :sparkles: Feat: Detail Selector
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
Labels: enhancement, 기능개발, 서현

#50 :bug: Fix : 회원가입 오류 해결
  src/pages/auths/authLogin/AuthLogin.jsx
  src/pages/auths/authSignup/AuthSignup.jsx
  src/pages/profile/Profile.jsx
  src/pages/profile/profileChangePassword/ProfileChangePassword.jsx
  src/pages/profile/profileMain/ProfileMain.jsx
Labels: bug, 기능개발, 희찬

#51 ✨ Feat : AI Service 디테일 페이지 - 이용후기 댓글 구현 (회원/공통)
  src/assets/images/icon/myReviewList.png
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#55 :sparkles: 페이지 이동 시 제일 상단으로 이동
  src/components/common/paging/Paging.jsx
  src/components/layouts/nabBar/NavBar.jsx
  src/pages/main/Main.jsx
Labels: enhancement, 서현

#56 🐛 Fix: Ai Service 디테일 페이지 - 클립보드 영역 오류 해결
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
Labels: bug, 유진

#57 ✨ Feat : AI Service 디테일 페이지 - 이용후기 별점 구현
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/list/List.jsx
  src/components/common/list/style.jsx
  src/pages/ai/AiServiceDetail.jsx
Labels: enhancement, 기능개발, 유진

#58 ✨Feat: 공지사항 디테일, 댓글 인풋컴포넌트생성
  src/assets/images/icon/bin.png
  src/assets/images/icon/pencil.png
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/common/commentInput/CommentInput.jsx
  src/components/common/commentInput/style.jsx
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/common/communityDetailContent/style.jsx
  src/components/common/editDelete/EditDelete.jsx
  src/components/common/editDelete/style.jsx
  src/pages/auths/authSignup/AuthSignup.jsx
  src/pages/community/communityDetail/DetailPage.jsx
  src/pages/community/communityDetail/style.jsx
  src/pages/profile/profileChangePassword/ProfileChangePassword.jsx
Labels: enhancement, 기능개발, 희찬, 디자인

#60 ✨ Feat : AI Service 디테일 페이지 - 기능소개
  src/assets/images/icon/descriptionBulbIcon.png
  src/assets/images/icon/descriptionFunctionIcon.png
  src/assets/images/icon/descriptionHeartIcon.png
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDescription/style.jsx
Labels: enhancement, 기능개발, 유진

#63 ✨ Feat: mdEditor 추가
  package-lock.json
  package.json
  src/components/common/aiServiceList/AiService.jsx
  src/components/layouts/nabBar/NavBar.jsx
  src/components/layouts/nabBar/style.jsx
  src/pages/auths/authLogin/AuthLogin.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/community/communityCreatePost/mdEditorStyle.css
Labels: enhancement, 서현, 디자인

#64 ✨ Feat : AI Service 디테일 페이지 - 데이터 및 디자인 수정
  package-lock.json
  package.json
  src/assets/images/icon/company.png
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/pages/ai/AiServiceDetail.jsx
Labels: enhancement, 기능개발, 유진

#65 💄 Style: AI Service 디테일 페이지 - 기능소개 아이콘 크기 변경
  package-lock.json
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDescription/style.jsx
Labels: 유진, 디자인

#66 💄 Style: List 컴포넌트 효과 추가
  src/components/common/list/List.jsx
  src/components/common/list/style.jsx
Labels: 유진, 디자인

#68 :lipstick: Style: 베너크기 키움
  src/App.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/layouts/footer/style.jsx
  src/components/main/mainBanner/banner1.png
  src/components/main/mainBanner/banner2.png
  src/components/main/mainBanner/banner3.png
  src/components/main/mainBanner/style.jsx
  src/pages/main/Main.jsx
  src/pages/main/style.jsx
Labels: documentation, enhancement, 서현

#71 🚀Deploy: 4차 배포테스트
  dist/assets/authBannerIcon-9a5a9827.svg
  dist/assets/banner1-203ac753.png
  dist/assets/banner1-b87c95c6.png
  dist/assets/banner2-5b1c62b3.png
  dist/assets/banner2-f5efcaff.png
  dist/assets/banner3-f2ad75c6.png
  dist/assets/communityBannerIcon-3e4b0317.svg
  dist/assets/descriptionBulbIcon-e8eacf3a.png
  dist/assets/index-31daf5db.js
  dist/assets/index-78e7cdfd.css
  dist/assets/index-87d10089.css
  dist/assets/index-a4b0b43f.js
  dist/assets/mypageBook-613150c4.svg
  dist/assets/mypageUserIcon-5b786312.png
  dist/assets/noticeBannerIcon-17156b52.svg
  dist/assets/reviewList-21e5d0ef.png
  dist/assets/suggestionBannerIcon-df43542c.svg
  dist/index.html
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
Labels: enhancement

#75 :sparkles: Feat: Pagination api
  src/components/common/aiServiceList/AiService.jsx
  src/components/common/aiServiceList/AiServiceList.jsx
  src/components/common/paging/ListView.jsx
  src/components/common/paging/Paging.jsx
  src/pages/main/Main.jsx
Labels: enhancement, 서현, 디자인

#76 ✨ Feat: 인공지능 서비스 디테일 불러오기 API 연동
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/pages/ai/AiServiceDetail.jsx
Labels: enhancement, 유진

#78 ✨ Feat: MainPage, SearchPage - Api 연결
  src/components/common/aiServiceList/AiService.jsx
  src/components/common/aiServiceList/AiServiceList.jsx
  src/components/common/highLightItem/HighLightItem.jsx
  src/components/common/highLightItem/style.jsx
  src/pages/main/Main.jsx
  src/pages/search/Search.jsx
Labels: enhancement, 기능개발, 서현

#79 🚀 Depoly : 5차 메인 반영
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/aiServiceList/AiService.jsx
  src/components/common/aiServiceList/AiServiceList.jsx
  src/components/common/aiServiceList/style.jsx
  src/components/common/highLightItem/HighLightItem.jsx
  src/components/common/highLightItem/style.jsx
  src/components/common/paging/ListView.jsx
  src/components/common/paging/Paging.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/main/Main.jsx
  src/pages/search/Search.jsx
Labels: 기능개발, 희찬

#83 🛠️ Connect: 1차 연동
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
  src/components/common/commonList/CommonList.jsx
  src/components/common/commonList/style.jsx
  src/components/common/list/List.jsx
  src/components/common/noticeList/NoticeList.jsx
  src/components/common/suggestionList/SuggestionList.jsx
  src/components/common/tipsList/TipsList.jsx
  src/components/common/tipsList/style.jsx
  src/components/community/communityCommon/CommunityCommon.jsx
  src/components/community/communityQna/CommunityQna.jsx
  src/components/community/communityTips/CommunityTips.jsx
Labels: enhancement, 희찬

#84 ✨ Feat: 인공지능 서비스 디테일 불러오기 API 연동
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/common/commonCommentList/CommonCommentList.jsx
  src/pages/ai/AiServiceDetail.jsx
Labels: enhancement, 유진

#85 ✨ feat : 게시판 목록 불러오기
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
  src/components/common/commonList/CommonList.jsx
  src/components/common/commonList/style.jsx
  src/components/common/list/List.jsx
  src/components/common/list/style.jsx
  src/components/common/noPage/NoPage.jsx
  src/components/common/noPage/style.jsx
  src/components/common/noticeList/NoticeList.jsx
  src/components/common/noticeList/style.jsx
  src/components/common/suggestionList/SuggestionList.jsx
  src/components/common/suggestionList/style.jsx
  src/components/common/tipsList/TipsList.jsx
  src/components/common/tipsList/style.jsx
  src/components/community/communityCommon/CommunityCommon.jsx
  src/components/community/communityCommonPost/CommunityCommonPost.jsx
  src/components/community/communityCommonPost/style.jsx
  src/components/community/communityQna/CommunityQna.jsx
  src/components/community/communityQnaPost/CommunityQnaPost.jsx
  src/components/community/communityQnaPost/style.jsx
  src/components/community/communityTips/CommunityTips.jsx
  src/components/community/communityTipsPost/CommunityTipsPost.jsx
  src/components/community/communityTipsPost/style.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/notice/Notice.jsx
  src/pages/suggestion/Suggestion.jsx
Labels: enhancement, 희찬

#87 🐛 Fix: import 오류 해결
  src/pages/community/communityDetail/DetailPage.jsx
Labels: bug, 유진

#90 :sparkles: Feat: AboutPage Layout
  src/components/common/aiServiceList/AiService.jsx
  src/components/layouts/nabBar/style.jsx
  src/pages/about/About.jsx
  src/pages/about/AboutSection1/AboutSection1_3d1.png
  src/pages/about/AboutSection1/AboutSection1_3d2.png
  src/pages/about/AboutSection1/AboutSection1_3d3.png
  src/pages/about/AboutSection1/AboutSection1_3d4.png
  src/pages/about/AboutSection1/AboutSection1_Banner.png
  src/pages/about/AboutSection1/AboutSection1_Ellipse.png
  src/pages/about/AboutSection1/AboutSection1_Smartphone.png
  src/pages/about/AboutSection2/AboutSection2_Des1.png
  src/pages/about/AboutSection2/AboutSection2_Des2.png
  src/pages/about/AboutSection2/AboutSection2_Earth.png
  src/pages/about/AboutSection2/AboutSection2_Hand.png
  src/pages/about/AboutSection2/AboutSection2_Person.png
  src/pages/about/AboutSection3/AboutSection3_TeamMoin.png
  src/pages/about/AboutSection3/AboutSection3_WhyMoin.png
  src/pages/about/AboutSection4/AboutSection4_ServiceDetail.png
  src/pages/about/AboutSection5/AboutSection5_GotoMain.png
  src/pages/about/AboutSection5/AboutSection5_Title.png
  src/pages/about/style.jsx
  src/style/globalStyle.js
Labels: enhancement, 서현, 디자인

#91 ✨ feat : AI 디테일
  src/components/aiServiceDetail/aiServiceDescription/style.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/commonCommentList/CommonCommentList.jsx
  src/components/common/editDelete/EditDelete.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/style.jsx
  src/pages/auths/authLogin/AuthLogin.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
Labels: enhancement, 기능개발, 희찬

#95 ✨ Feat: SEO최적화 1단계
  index.html
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/pages/main/Main.jsx
Labels: 희찬, 디자인

#97 💄Style: 메인페이지 애니메이션, 폰트 적용
  src/components/main/mainBanner/style.jsx
  src/pages/main/style.jsx
  src/style/globalStyle.js
Labels: 희찬, 디자인

#94 💄 Style: Footer, KeywordColor
  src/components/common/keyword/Keyword.jsx
  src/components/layouts/footer/FooterBar.jsx
  src/components/layouts/nabBar/NavBar.jsx
  src/components/layouts/nabBar/style.jsx
  src/components/main/mainCategory/mainCategorySwiper.css
  src/pages/about/About.jsx
Labels: 서현, 디자인

#98 ✨ Feat: 마이페이지 API 연동
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/common/modal/Modal.jsx
  src/components/common/modal/style.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/profile/profileComment/ProfileComment.jsx
  src/pages/profile/profileFavorite/ProfileFavorite.jsx
  src/pages/profile/profileFavoritePost/ProfileFavoritePost.jsx
  src/pages/profile/profileMain/ProfileMain.jsx
  src/pages/profile/profilePost/ProfilePost.jsx
Labels: enhancement, 유진

#102 :lipstick: Style: AboutPage animation delay
  src/pages/about/About.jsx
  src/pages/about/AboutSection1/AboutSection1_Smartphone1.png
  src/pages/about/AboutSection1/AboutSection1_Smartphone2.png
Labels: 서현, 디자인

#104 ✨Feat:최종 1차 수정
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/commonList/CommonList.jsx
  src/components/common/commonList/style.jsx
  src/components/common/list/List.jsx
  src/components/common/list/style.jsx
  src/components/common/noticeBanner/NoticeBanner.jsx
  src/components/common/noticeBanner/style.jsx
  src/components/common/noticeList/NoticeList.jsx
  src/components/common/noticeList/style.jsx
  src/components/common/suggestionList/SuggestionList.jsx
  src/components/common/suggestionList/style.jsx
  src/components/common/tipsList/TipsList.jsx
  src/components/common/tipsList/style.jsx
  src/components/community/communityQna/CommunityQna.jsx
  src/components/community/communityTips/CommunityTips.jsx
  src/components/community/communtiyDetailPageType/style.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/community/communityCreatePost/style.jsx
  src/pages/community/communityDetail/DetailPage.jsx
  src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx
Labels: 기능개발, 희찬

#106 ✨Feat: 댓글기능
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/common/commentInput/CommentInput.jsx
  src/components/common/commentInput/style.jsx
  src/components/common/commonCommentList/CommonCommentList.jsx
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/common/editDelete/EditDelete.jsx
  src/components/common/noticeList/NoticeList.jsx
  src/components/common/noticeList/style.jsx
  src/components/common/suggestionList/SuggestionList.jsx
  src/components/common/suggestionList/style.jsx
  src/pages/community/communityDetail/DetailPage.jsx
  src/pages/suggestion/suggestionDetail/SuggestionDetailPage.jsx
Labels: 기능개발, 희찬

#107 ✨ Feat: 회의 수정 사항 적용
  src/assets/images/icon/loginModalMoin.png
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/common/modal/loginModal/LoginModal.jsx
  src/components/common/modal/loginModal/style.jsx
  src/components/profile/profileFavoritePost/ProfileList.jsx
  src/components/profile/profileFavoritePost/style.jsx
  src/pages/profile/Profile.jsx
Labels: enhancement, 기능개발, 유진, 디자인

#108 ✨ Feat: Ai Service 디테일 페이지 - 비회원 별점 등록 클릭 시 모달창 띄우기
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
Labels: enhancement, 유진

#109 ✨Feat: 게시글, 마이페이지 수정
  package-lock.json
  package.json
  src/components/auths/authContentBox/AuthContentBox.jsx
  src/components/auths/authSocialButton/style.jsx
  src/components/common/commonList/CommonList.jsx
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/common/tipsList/style.jsx
  src/components/community/communtiyDetailPageType/CommuntiyDetailPageType.jsx
  src/pages/auths/authLogin/AuthLogin.jsx
  src/pages/auths/authLogin/kakaoAuth.jsx
  src/pages/auths/authSignup/style.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/community/communityCreatePost/style.jsx
  src/pages/community/communityDetail/DetailPage.jsx
  src/pages/community/communityEdit/CommunityEdit.jsx
  src/pages/community/communityEdit/style.jsx
  src/pages/profile/profileMain/ProfileMain.jsx
  src/pages/profile/profileMain/style.jsx
  src/pages/profile/profileModify/ProfileModify.jsx
  src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx
  src/pages/suggestion/suggestionCreate/style.jsx
  src/pages/suggestion/suggestionDetail/SuggestionDetailPage.jsx
  src/pages/suggestion/suggestionDetail/style.jsx
Labels: 기능개발, 희찬, 디자인

#110 💄 Style: AI Service Detail 반응형
  src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
  src/components/aiServiceDetail/aiServiceDescription/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/main/mainCategory/style.jsx
  src/pages/ai/style.jsx
  src/pages/main/style.jsx
Labels: 서현, 디자인

#111 ✨ Feat: 마이페이지 - 좋아요한 게시글 구현
  src/components/profile/profileCommunityList/ProfileCommon.jsx
  src/components/profile/profileCommunityList/style.jsx
  src/components/profile/profileFavoritePost/ProfileList.jsx
  src/components/profile/profileList/ProfileList.jsx
  src/components/profile/profileList/style.jsx
  src/pages/profile/profileFavoritePost/ProfileFavoritePost.jsx
  src/pages/profile/profileFavoritePost/style.jsx
Labels: 기능개발, 유진, 디자인

#112 💄 Style: 반응형
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/common/aiServiceList/style.jsx
  src/components/common/commonCommentList/style.jsx
Labels: 서현, 디자인

#117 ✨ Feat: List 컴포넌트 통합
  src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/common/postList/PostList.jsx
  src/components/common/postList/style.jsx
  src/components/common/이제 필요없는.../commonList/CommonList.jsx
  src/components/common/이제 필요없는.../commonList/style.jsx
  src/components/common/이제 필요없는.../list/List.jsx
  src/components/common/이제 필요없는.../list/style.jsx
  src/components/common/이제 필요없는.../noticeList/NoticeList.jsx
  src/components/common/이제 필요없는.../noticeList/style.jsx
  src/components/common/이제 필요없는.../suggestionList/SuggestionList.jsx
  src/components/common/이제 필요없는.../suggestionList/style.jsx
  src/components/common/이제 필요없는.../tipsList/TipsList.jsx
  src/components/common/이제 필요없는.../tipsList/style.jsx
  src/components/community/communityCommon/CommunityCommon.jsx
  src/components/community/communityQna/CommunityQna.jsx
  src/components/community/communityTips/CommunityTips.jsx
  src/pages/ai/AiServiceDetail.jsx
  src/pages/ai/style.jsx
  src/pages/community/Community.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/community/style.jsx
  src/pages/notice/Notice.jsx
  src/pages/notice/style.jsx
  src/pages/profile/profileComment/ProfileComment.jsx
  src/pages/profile/profileFavoritePost/ProfileFavoritePost.jsx
  src/pages/profile/profilePost/ProfilePost.jsx
  src/pages/suggestion/Suggestion.jsx
  src/pages/suggestion/style.jsx
Labels: 기능개발, 서현, 디자인

#116 ✨ Feat: 마이페이지 - 내가 작성한 댓글 라우팅
  src/components/profile/profileList/ProfileList.jsx
Labels: enhancement, 유진

#118 :sparkles: Feat: about 애니메이션 속도 조절
  src/components/common/postList/PostList.jsx
  src/components/common/postList/PostMobileList.jsx
  src/components/common/postList/PostMonitorList.jsx
  src/pages/about/About.jsx
  src/pages/about/animation.css
  src/pages/notice/Notice.jsx
Labels: enhancement, 서현, 디자인

#119 :sparkles: Feat: PostList
  src/components/common/postList/PostList.jsx
  src/components/common/postList/PostMonitorList.jsx
  src/pages/about/About.jsx
  src/pages/about/AboutSection6/AboutSection6_AboutUS.svg
  src/pages/about/AboutSection6/AboutSection6_MoinStory.svg
  src/pages/about/AboutSection6/aboutUs1.jpeg
  src/pages/about/AboutSection6/aboutUs2.jpeg
  src/pages/about/AboutSection6/aboutUs3.jpeg
  src/pages/about/animation.css
  src/pages/about/style.jsx
Labels: enhancement, 기능개발, 서현

#124 :sparkles: Feat: 비밀번호 재설정 기능
  src/pages/auths/authReset/AuthReset.jsx
  src/pages/auths/authReseting/AuthReseting.jsx
  src/pages/auths/authReseting/style.jsx
  src/router.jsx
Labels: 희찬

#127 :bug: Fix: 경로수정
  src/components/common/postList/PostList.jsx
  src/components/common/postList/style.jsx
  src/pages/about/About.jsx
Labels: 서현

#128 :sparkles: Feat: file drop down
  package-lock.json
  package.json
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/common/communityDetailContent/markdown-styles.module.css
  src/components/common/noticeBanner/style.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx
Labels: enhancement, 기능개발, 희찬

#129 🚀Deploy: 16차 main반영
  package-lock.json
  package.json
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/common/communityDetailContent/markdown-styles.module.css
  src/components/common/noticeBanner/style.jsx
  src/components/common/postList/PostList.jsx
  src/components/common/postList/style.jsx
  src/pages/about/About.jsx
  src/pages/community/communityCreatePost/CommunityCreatPost.jsx
  src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx
Labels: 희찬

#130 💄 Style: 반응형
  src/App.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
  src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
  src/components/common/postList/PostList.jsx
  src/components/common/postList/style.jsx
  src/components/layouts/nabBar/NavBar.jsx
  src/pages/ai/style.jsx
Labels: 서현, 디자인

#131 ✨ Feat: 어바웃페이지 완료
  src/pages/about/About.jsx
  src/pages/about/AboutSection6/AboutSection6_AboutUS.svg
  src/pages/about/AboutSection6/AboutSection6_AboutUs.png
  src/pages/about/AboutSection6/AboutSection6_DGU.png
  src/pages/about/AboutSection6/AboutSection6_Making.png
  src/pages/about/AboutSection6/AboutSection6_MoinStory.png
  src/pages/about/AboutSection6/AboutSection6_MoinStory.svg
  src/pages/about/style.jsx
Labels: 서현, 디자인

#133 ✨ Feat: markdown css
  src/components/common/communityDetailContent/CommunityDetailContent.jsx
  src/components/main/mainBanner/MainBannerList.jsx
  src/components/main/mainBanner/banner1.png
  src/components/main/mainBanner/banner2.png
  src/components/main/mainBanner/banner3.png
  src/components/main/mainBanner/bannerMobile1.svg
  src/components/main/mainBanner/img/DeepDive.jpeg
  src/components/main/mainBanner/img/DeepDiveMovbile.jpeg
  src/components/main/mainBanner/img/EventPresent.png
  src/components/main/mainBanner/img/EventPresentMobile.png
  src/style/globalStyle.js
Labels: enhancement, 기능개발, 서현
